spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/ghy1?serverTimezone=Asia/Seoul
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  autoconfigure:   # 운영환경에서만 redis를 사용하도록 설정
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      #- org.springframework.boot.autoconfigure.session.SessionAutoConfiguration   # 세션을 redis에 저장
logging:
  level:
    com.ll.gooHaeYu: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
tossPayments:
  successUrl: "http://localhost:5173/payment/success"
  failUrl: "http://localhost:5173/payment/fail"
app:
  init-run: false
